// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

/*
Package gobuildmaster is a generated protocol buffer package.

It is generated from these files:
	master.proto

It has these top-level messages:
	Config
	Intent
	NIntent
	Empty
	CompareResponse
*/
package gobuildmaster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gobuildslave "github.com/brotherlogic/gobuildslave/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Redundancy int32

const (
	Redundancy_UNKNOWN   Redundancy = 0
	Redundancy_SOLO      Redundancy = 1
	Redundancy_REDUNDANT Redundancy = 2
	Redundancy_GLOBAL    Redundancy = 3
)

var Redundancy_name = map[int32]string{
	0: "UNKNOWN",
	1: "SOLO",
	2: "REDUNDANT",
	3: "GLOBAL",
}
var Redundancy_value = map[string]int32{
	"UNKNOWN":   0,
	"SOLO":      1,
	"REDUNDANT": 2,
	"GLOBAL":    3,
}

func (x Redundancy) String() string {
	return proto.EnumName(Redundancy_name, int32(x))
}
func (Redundancy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Config struct {
	Intents  []*Intent  `protobuf:"bytes,1,rep,name=intents" json:"intents,omitempty"`
	Nintents []*NIntent `protobuf:"bytes,2,rep,name=nintents" json:"nintents,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetIntents() []*Intent {
	if m != nil {
		return m.Intents
	}
	return nil
}

func (m *Config) GetNintents() []*NIntent {
	if m != nil {
		return m.Nintents
	}
	return nil
}

type Intent struct {
	Spec  *gobuildslave.JobSpec `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
	Count int32                 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *Intent) Reset()                    { *m = Intent{} }
func (m *Intent) String() string            { return proto.CompactTextString(m) }
func (*Intent) ProtoMessage()               {}
func (*Intent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Intent) GetSpec() *gobuildslave.JobSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Intent) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type NIntent struct {
	Job        *gobuildslave.Job `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
	Count      int32             `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Redundancy Redundancy        `protobuf:"varint,3,opt,name=redundancy,enum=gobuildmaster.Redundancy" json:"redundancy,omitempty"`
}

func (m *NIntent) Reset()                    { *m = NIntent{} }
func (m *NIntent) String() string            { return proto.CompactTextString(m) }
func (*NIntent) ProtoMessage()               {}
func (*NIntent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NIntent) GetJob() *gobuildslave.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *NIntent) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *NIntent) GetRedundancy() Redundancy {
	if m != nil {
		return m.Redundancy
	}
	return Redundancy_UNKNOWN
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CompareResponse struct {
	Current *Config `protobuf:"bytes,1,opt,name=current" json:"current,omitempty"`
	Desired *Config `protobuf:"bytes,2,opt,name=desired" json:"desired,omitempty"`
}

func (m *CompareResponse) Reset()                    { *m = CompareResponse{} }
func (m *CompareResponse) String() string            { return proto.CompactTextString(m) }
func (*CompareResponse) ProtoMessage()               {}
func (*CompareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CompareResponse) GetCurrent() *Config {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *CompareResponse) GetDesired() *Config {
	if m != nil {
		return m.Desired
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "gobuildmaster.Config")
	proto.RegisterType((*Intent)(nil), "gobuildmaster.Intent")
	proto.RegisterType((*NIntent)(nil), "gobuildmaster.NIntent")
	proto.RegisterType((*Empty)(nil), "gobuildmaster.Empty")
	proto.RegisterType((*CompareResponse)(nil), "gobuildmaster.CompareResponse")
	proto.RegisterEnum("gobuildmaster.Redundancy", Redundancy_name, Redundancy_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoBuildMaster service

type GoBuildMasterClient interface {
	Compare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CompareResponse, error)
}

type goBuildMasterClient struct {
	cc *grpc.ClientConn
}

func NewGoBuildMasterClient(cc *grpc.ClientConn) GoBuildMasterClient {
	return &goBuildMasterClient{cc}
}

func (c *goBuildMasterClient) Compare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CompareResponse, error) {
	out := new(CompareResponse)
	err := grpc.Invoke(ctx, "/gobuildmaster.GoBuildMaster/Compare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoBuildMaster service

type GoBuildMasterServer interface {
	Compare(context.Context, *Empty) (*CompareResponse, error)
}

func RegisterGoBuildMasterServer(s *grpc.Server, srv GoBuildMasterServer) {
	s.RegisterService(&_GoBuildMaster_serviceDesc, srv)
}

func _GoBuildMaster_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildMasterServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildmaster.GoBuildMaster/Compare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildMasterServer).Compare(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoBuildMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gobuildmaster.GoBuildMaster",
	HandlerType: (*GoBuildMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compare",
			Handler:    _GoBuildMaster_Compare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}

func init() { proto.RegisterFile("master.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x8f, 0x93, 0x40,
	0x1c, 0xc5, 0x97, 0xb2, 0x85, 0xf5, 0xbb, 0x56, 0x71, 0xb2, 0x1a, 0xdc, 0x83, 0x21, 0x78, 0xa9,
	0x1e, 0x20, 0xc1, 0xc4, 0xc4, 0x8b, 0x49, 0xb7, 0x6d, 0x9a, 0x6a, 0x85, 0x64, 0x6a, 0xe3, 0x99,
	0x1f, 0x23, 0xc5, 0x94, 0x19, 0x32, 0x33, 0x98, 0xf4, 0xe4, 0xbf, 0x6e, 0x18, 0x68, 0x6d, 0xa9,
	0x7b, 0x83, 0x99, 0xcf, 0x7b, 0xef, 0xfb, 0xbe, 0x19, 0x78, 0x5a, 0xc6, 0x42, 0x12, 0xee, 0x55,
	0x9c, 0x49, 0x86, 0x46, 0x39, 0x4b, 0xea, 0x62, 0x97, 0xb5, 0x87, 0xf7, 0x1f, 0xf3, 0x42, 0x6e,
	0xeb, 0xc4, 0x4b, 0x59, 0xe9, 0x27, 0x9c, 0xc9, 0x2d, 0xe1, 0x3b, 0x96, 0x17, 0xa9, 0xdf, 0x61,
	0x62, 0x17, 0xff, 0x26, 0xbe, 0x92, 0xfa, 0xea, 0xbb, 0xb5, 0x71, 0x4b, 0x30, 0xa6, 0x8c, 0xfe,
	0x2c, 0x72, 0xe4, 0x83, 0x59, 0x50, 0x49, 0xa8, 0x14, 0xb6, 0xe6, 0xe8, 0xe3, 0xdb, 0xe0, 0xa5,
	0x77, 0x16, 0xe1, 0x2d, 0xd5, 0x2d, 0x3e, 0x50, 0x28, 0x80, 0x1b, 0x7a, 0x50, 0x0c, 0x94, 0xe2,
	0x55, 0x4f, 0x11, 0x76, 0x92, 0x23, 0xe7, 0x2e, 0xc1, 0x68, 0xcf, 0xd0, 0x3b, 0xb8, 0x16, 0x15,
	0x49, 0x6d, 0xcd, 0xd1, 0x4e, 0xb3, 0xda, 0xd9, 0xbe, 0xb0, 0x64, 0x5d, 0x91, 0x14, 0x2b, 0x04,
	0xdd, 0xc1, 0x30, 0x65, 0x35, 0x95, 0xf6, 0xc0, 0xd1, 0xc6, 0x43, 0xdc, 0xfe, 0xb8, 0x7f, 0xc0,
	0xec, 0xfc, 0xd1, 0x5b, 0xd0, 0x7f, 0xb1, 0xa4, 0xb3, 0x7a, 0x71, 0x61, 0x85, 0x9b, 0xdb, 0xff,
	0xbb, 0xa0, 0x4f, 0x00, 0x9c, 0x64, 0x35, 0xcd, 0x62, 0x9a, 0xee, 0x6d, 0xdd, 0xd1, 0xc6, 0xcf,
	0x82, 0xd7, 0xbd, 0x1a, 0xf8, 0x08, 0xe0, 0x13, 0xd8, 0x35, 0x61, 0x38, 0x2f, 0x2b, 0xb9, 0x77,
	0x05, 0x3c, 0x9f, 0xb2, 0xb2, 0x8a, 0x39, 0xc1, 0x44, 0x54, 0x8c, 0x0a, 0xd2, 0x2c, 0x33, 0xad,
	0x39, 0x27, 0x54, 0xf6, 0x0b, 0x76, 0x9e, 0xed, 0xd2, 0xf1, 0x81, 0x6a, 0x04, 0x19, 0x11, 0x05,
	0x27, 0x99, 0x9a, 0xef, 0x71, 0x41, 0x47, 0xbd, 0xff, 0x0c, 0xf0, 0x6f, 0x2e, 0x74, 0x0b, 0xe6,
	0x26, 0xfc, 0x1a, 0x46, 0x3f, 0x42, 0xeb, 0x0a, 0xdd, 0xc0, 0xf5, 0x3a, 0x5a, 0x45, 0x96, 0x86,
	0x46, 0xf0, 0x04, 0xcf, 0x67, 0x9b, 0x70, 0x36, 0x09, 0xbf, 0x5b, 0x03, 0x04, 0x60, 0x2c, 0x56,
	0xd1, 0xc3, 0x64, 0x65, 0xe9, 0x01, 0x86, 0xd1, 0x82, 0x3d, 0x34, 0x01, 0xdf, 0x54, 0x00, 0x9a,
	0x80, 0xd9, 0xb5, 0x40, 0x77, 0xbd, 0x6c, 0x55, 0xf3, 0xfe, 0xcd, 0xc5, 0x44, 0x67, 0x9d, 0xdd,
	0xab, 0xc4, 0x50, 0x6f, 0xea, 0xc3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x68, 0xa5, 0x7b,
	0xaa, 0x02, 0x00, 0x00,
}
