// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package gobuildmaster

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/gobuildslave/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Redundancy int32

const (
	Redundancy_UNKNOWN   Redundancy = 0
	Redundancy_SOLO      Redundancy = 1
	Redundancy_REDUNDANT Redundancy = 2
	Redundancy_GLOBAL    Redundancy = 3
)

var Redundancy_name = map[int32]string{
	0: "UNKNOWN",
	1: "SOLO",
	2: "REDUNDANT",
	3: "GLOBAL",
}

var Redundancy_value = map[string]int32{
	"UNKNOWN":   0,
	"SOLO":      1,
	"REDUNDANT": 2,
	"GLOBAL":    3,
}

func (x Redundancy) String() string {
	return proto.EnumName(Redundancy_name, int32(x))
}

func (Redundancy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

type Config struct {
	Intents              []*Intent  `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	Nintents             []*NIntent `protobuf:"bytes,2,rep,name=nintents,proto3" json:"nintents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetIntents() []*Intent {
	if m != nil {
		return m.Intents
	}
	return nil
}

func (m *Config) GetNintents() []*NIntent {
	if m != nil {
		return m.Nintents
	}
	return nil
}

type Intent struct {
	Spec                 *proto1.JobSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Count                int32           `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Intent) Reset()         { *m = Intent{} }
func (m *Intent) String() string { return proto.CompactTextString(m) }
func (*Intent) ProtoMessage()    {}
func (*Intent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *Intent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intent.Unmarshal(m, b)
}
func (m *Intent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intent.Marshal(b, m, deterministic)
}
func (m *Intent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intent.Merge(m, src)
}
func (m *Intent) XXX_Size() int {
	return xxx_messageInfo_Intent.Size(m)
}
func (m *Intent) XXX_DiscardUnknown() {
	xxx_messageInfo_Intent.DiscardUnknown(m)
}

var xxx_messageInfo_Intent proto.InternalMessageInfo

func (m *Intent) GetSpec() *proto1.JobSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Intent) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type NIntent struct {
	Job                  *proto1.Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Count                int32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Redundancy           Redundancy  `protobuf:"varint,3,opt,name=redundancy,proto3,enum=gobuildmaster.Redundancy" json:"redundancy,omitempty"`
	NoMaster             bool        `protobuf:"varint,4,opt,name=no_master,json=noMaster,proto3" json:"no_master,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NIntent) Reset()         { *m = NIntent{} }
func (m *NIntent) String() string { return proto.CompactTextString(m) }
func (*NIntent) ProtoMessage()    {}
func (*NIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *NIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NIntent.Unmarshal(m, b)
}
func (m *NIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NIntent.Marshal(b, m, deterministic)
}
func (m *NIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NIntent.Merge(m, src)
}
func (m *NIntent) XXX_Size() int {
	return xxx_messageInfo_NIntent.Size(m)
}
func (m *NIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_NIntent.DiscardUnknown(m)
}

var xxx_messageInfo_NIntent proto.InternalMessageInfo

func (m *NIntent) GetJob() *proto1.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *NIntent) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *NIntent) GetRedundancy() Redundancy {
	if m != nil {
		return m.Redundancy
	}
	return Redundancy_UNKNOWN
}

func (m *NIntent) GetNoMaster() bool {
	if m != nil {
		return m.NoMaster
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CompareResponse struct {
	Current              *Config  `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Desired              *Config  `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareResponse) Reset()         { *m = CompareResponse{} }
func (m *CompareResponse) String() string { return proto.CompactTextString(m) }
func (*CompareResponse) ProtoMessage()    {}
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *CompareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareResponse.Unmarshal(m, b)
}
func (m *CompareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareResponse.Marshal(b, m, deterministic)
}
func (m *CompareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareResponse.Merge(m, src)
}
func (m *CompareResponse) XXX_Size() int {
	return xxx_messageInfo_CompareResponse.Size(m)
}
func (m *CompareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompareResponse proto.InternalMessageInfo

func (m *CompareResponse) GetCurrent() *Config {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *CompareResponse) GetDesired() *Config {
	if m != nil {
		return m.Desired
	}
	return nil
}

func init() {
	proto.RegisterEnum("gobuildmaster.Redundancy", Redundancy_name, Redundancy_value)
	proto.RegisterType((*Config)(nil), "gobuildmaster.Config")
	proto.RegisterType((*Intent)(nil), "gobuildmaster.Intent")
	proto.RegisterType((*NIntent)(nil), "gobuildmaster.NIntent")
	proto.RegisterType((*Empty)(nil), "gobuildmaster.Empty")
	proto.RegisterType((*CompareResponse)(nil), "gobuildmaster.CompareResponse")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x6f, 0x95, 0x30,
	0x18, 0xc6, 0xd7, 0xf3, 0x01, 0xec, 0x9d, 0x47, 0xb1, 0x99, 0x06, 0x67, 0x62, 0x08, 0xde, 0xa0,
	0x17, 0x90, 0x60, 0x62, 0xe2, 0x8d, 0xc9, 0xd9, 0x47, 0x96, 0xe9, 0x11, 0x92, 0xce, 0xc5, 0x4b,
	0xc3, 0x47, 0x65, 0x98, 0x43, 0x4b, 0xda, 0x62, 0xb2, 0xff, 0xc5, 0x3f, 0xd6, 0xd0, 0x72, 0xe6,
	0xc6, 0xf4, 0x8e, 0xf6, 0xfd, 0x3d, 0xef, 0xf3, 0x3c, 0x00, 0x3c, 0x6a, 0x73, 0xa9, 0xa8, 0x88,
	0x3a, 0xc1, 0x15, 0xc7, 0xab, 0x9a, 0x17, 0x7d, 0xb3, 0xad, 0xcc, 0xe5, 0xd1, 0xfb, 0xba, 0x51,
	0xd7, 0x7d, 0x11, 0x95, 0xbc, 0x8d, 0x0b, 0xc1, 0xd5, 0x35, 0x15, 0x5b, 0x5e, 0x37, 0x65, 0x3c,
	0x62, 0x72, 0x9b, 0xff, 0xa2, 0xb1, 0x96, 0xc6, 0xfa, 0xd9, 0xac, 0x09, 0x5a, 0xb0, 0x4e, 0x38,
	0xfb, 0xd1, 0xd4, 0x38, 0x06, 0xbb, 0x61, 0x8a, 0x32, 0x25, 0x3d, 0xe4, 0xcf, 0xc3, 0x83, 0xe4,
	0x59, 0x74, 0xcf, 0x22, 0xba, 0xd0, 0x53, 0xb2, 0xa3, 0x70, 0x02, 0x0e, 0xdb, 0x29, 0x66, 0x5a,
	0xf1, 0x7c, 0xa2, 0x48, 0x47, 0xc9, 0x2d, 0x17, 0x5c, 0x80, 0x65, 0xee, 0xf0, 0x1b, 0x58, 0xc8,
	0x8e, 0x96, 0x1e, 0xf2, 0xd1, 0x5d, 0x2f, 0x93, 0xed, 0x13, 0x2f, 0x2e, 0x3b, 0x5a, 0x12, 0x8d,
	0xe0, 0x43, 0x58, 0x96, 0xbc, 0x67, 0xca, 0x9b, 0xf9, 0x28, 0x5c, 0x12, 0x73, 0x08, 0x7e, 0x23,
	0xb0, 0x47, 0x03, 0xfc, 0x1a, 0xe6, 0x3f, 0x79, 0x31, 0xee, 0x7a, 0xfa, 0x60, 0x17, 0x19, 0xa6,
	0xff, 0x5e, 0x83, 0x3f, 0x00, 0x08, 0x5a, 0xf5, 0xac, 0xca, 0x59, 0x79, 0xe3, 0xcd, 0x7d, 0x14,
	0x3e, 0x4e, 0x5e, 0x4c, 0x7a, 0x90, 0x5b, 0x80, 0xdc, 0x81, 0xf1, 0x4b, 0xd8, 0x67, 0xfc, 0xbb,
	0x61, 0xbc, 0x85, 0x8f, 0x42, 0x87, 0x38, 0x8c, 0x7f, 0xd1, 0xe7, 0xc0, 0x86, 0xe5, 0x59, 0xdb,
	0xa9, 0x9b, 0x40, 0xc2, 0x93, 0x13, 0xde, 0x76, 0xb9, 0xa0, 0x84, 0xca, 0x8e, 0x33, 0x49, 0x87,
	0x57, 0x5d, 0xf6, 0x42, 0x50, 0xa6, 0xa6, 0xf5, 0x47, 0x43, 0xf3, 0x49, 0xc8, 0x8e, 0x1a, 0x04,
	0x15, 0x95, 0x8d, 0xa0, 0x95, 0x0e, 0xff, 0x7f, 0xc1, 0x48, 0xbd, 0xfd, 0x08, 0xf0, 0x37, 0x34,
	0x3e, 0x00, 0xfb, 0x2a, 0xfd, 0x9c, 0x66, 0xdf, 0x52, 0x77, 0x0f, 0x3b, 0xb0, 0xb8, 0xcc, 0x36,
	0x99, 0x8b, 0xf0, 0x0a, 0xf6, 0xc9, 0xd9, 0xe9, 0x55, 0x7a, 0xba, 0x4e, 0xbf, 0xba, 0x33, 0x0c,
	0x60, 0x9d, 0x6f, 0xb2, 0xe3, 0xf5, 0xc6, 0x9d, 0x27, 0x04, 0x56, 0xe7, 0xfc, 0x78, 0x30, 0x30,
	0x75, 0xf0, 0x1a, 0xec, 0xb1, 0x05, 0x3e, 0x9c, 0x78, 0xeb, 0x9a, 0x47, 0xaf, 0x1e, 0x24, 0xba,
	0xd7, 0x39, 0xd8, 0x2b, 0x2c, 0xfd, 0xc7, 0xbd, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x5d,
	0xaf, 0xec, 0xc8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoBuildMasterClient is the client API for GoBuildMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoBuildMasterClient interface {
	Compare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CompareResponse, error)
}

type goBuildMasterClient struct {
	cc *grpc.ClientConn
}

func NewGoBuildMasterClient(cc *grpc.ClientConn) GoBuildMasterClient {
	return &goBuildMasterClient{cc}
}

func (c *goBuildMasterClient) Compare(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CompareResponse, error) {
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, "/gobuildmaster.GoBuildMaster/Compare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoBuildMasterServer is the server API for GoBuildMaster service.
type GoBuildMasterServer interface {
	Compare(context.Context, *Empty) (*CompareResponse, error)
}

func RegisterGoBuildMasterServer(s *grpc.Server, srv GoBuildMasterServer) {
	s.RegisterService(&_GoBuildMaster_serviceDesc, srv)
}

func _GoBuildMaster_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildMasterServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildmaster.GoBuildMaster/Compare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildMasterServer).Compare(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoBuildMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gobuildmaster.GoBuildMaster",
	HandlerType: (*GoBuildMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compare",
			Handler:    _GoBuildMaster_Compare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
